# Generated by Django 3.2.3 on 2024-01-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capi', '0002_auto_20240103_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.TextField(default='', primary_key=True, serialize=False),
        ),
    ]
