# Generated by Django 3.2.3 on 2024-01-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capi', '0003_alter_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
