# Generated by Django 3.2.3 on 2024-01-05 13:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('capi', '0006_auto_20240105_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.TextField(),
        ),
    ]
