# Generated by Django 3.2.3 on 2024-01-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capi', '0008_alter_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='searched_key',
            field=models.TextField(default=''),
        ),
    ]
