# Generated by Django 3.2.3 on 2024-01-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capi', '0010_alter_video_searched_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='searched_key',
            field=models.TextField(),
        ),
    ]
